language: node_js
node_js:
  - node
  - 6
  - 5
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8

before_script:
  - "npm install -g jshint"

after_script:
  - "jshint --config=.jshintrc ."

env:
  - DOCKER_SOCKET="test"
  - TRAVIS=travis CXX=g++-4.8
